@url = http://localhost:4000/api/v1/user
@id = 60a333c0dd4b139c5b898111

###
POST {{url}}/register
Content-Type: application/json

{
  "name": "asdf",
  "email": "asdf@gmail.com",
  "password": "asdf"
}

###
POST {{url}}/login
Content-Type: application/json

{
  "email": "asdf@gmail.com",
  "password": "asdf"
}

